import Control from "sap/ui/core/Control";
import RenderManager from "sap/ui/core/RenderManager";
import ResponsivePopover from "sap/m/ResponsivePopover";
import Button from "sap/m/Button";
import Input from "sap/m/Input";
import DateRangeSelection from "sap/m/DateRangeSelection";
import List from "sap/m/List";
import StandardListItem from "sap/m/StandardListItem";
import Select from "sap/m/Select";
import Item from "sap/ui/core/Item";
import VBox from "sap/m/VBox";
import Label from "sap/m/Label";
import IconPool from "sap/ui/core/IconPool";

export type FilterType = "text" | "category" | "dateRange" | "slaStatus" | "none";
type SortState = "none" | "asc" | "desc";

type TextFilterValue = { query?: string };
type CategoryFilterValue = { selected?: string[] };
type DateFilterValue = { from?: Date | string | null; to?: Date | string | null };
type SlaFilterValue = { selection?: "all" | "overdue" | "onTrack" };

/**
 * Reusable table-column header with a sortable label and a type-aware filter popover.
 * The parent controller owns table state and reacts to the events emitted by this control.
 */
export default class TableHeaderCell extends Control {
    // --- auto-generated by Control.extend metadata; declared here for TS ---
    declare public getText: () => string;
    declare public getColumnKey: () => string;
    declare public getSortField: () => string;
    declare public getSortable: () => boolean;
    declare public getSortState: () => string;
    declare public getFilterType: () => string;
    declare public getFilterActive: () => boolean;
    declare public getCategoryOptions: () => string;
    declare public getFilterValue: () => any;

    declare public fireSortChange: (mParams: { columnKey: string; sortField: string; sortState: string }) => this;
    declare public fireFilterChange: (mParams: { columnKey: string; filterType: string; value: any }) => this;
    declare public fireFilterClear: (mParams: { columnKey: string }) => this;

    public static metadata = {
        properties: {
            text: { type: "string", defaultValue: "" },
            columnKey: { type: "string", defaultValue: "" },
            sortField: { type: "string", defaultValue: "" },
            sortable: { type: "boolean", defaultValue: true },
            sortState: { type: "string", defaultValue: "none" },
            filterType: { type: "string", defaultValue: "none" },
            filterActive: { type: "boolean", defaultValue: false },
            categoryOptions: { type: "string", defaultValue: "[]" },
            filterValue: { type: "object", defaultValue: null }
        },
        events: {
            sortChange: {
                parameters: {
                    columnKey: { type: "string" },
                    sortField: { type: "string" },
                    sortState: { type: "string" }
                }
            },
            filterChange: {
                parameters: {
                    columnKey: { type: "string" },
                    filterType: { type: "string" },
                    value: { type: "object" }
                }
            },
            filterClear: {
                parameters: {
                    columnKey: { type: "string" }
                }
            }
        }
    };

    private _oPopover: ResponsivePopover | null = null;
    private _oTextInput: Input | null = null;
    private _oCategoryList: List | null = null;
    private _oDateRange: DateRangeSelection | null = null;
    private _oSlaSelect: Select | null = null;

    public static renderer = {
        apiVersion: 2,
        render: (oRm: RenderManager, oControl: TableHeaderCell): void => {
            const sSortState = oControl.getSortState() as SortState;
            const bSortable = oControl.getSortable();
            const bCanFilter = oControl.getFilterType() !== "none";
            const sAlignment = (oControl.getParent() as any)?.getHAlign?.() || "Left";

            oRm.openStart("div", oControl);
            oRm.class("thcRoot");
            oRm.class(`thcAlign${sAlignment}`);
            if (bSortable) {
                oRm.class("thcSortable");
            }
            if (oControl.getFilterActive()) {
                oRm.class("thcHasActiveFilter");
            }
            oRm.openEnd();

            // The label group is the only in-flow content, allowing the parent
            // Column hAlign setting to position it consistently with table cells.
            oRm.openStart("span");
            oRm.class("thcLabelGroup");
            oRm.openEnd();

            oRm.openStart("span");
            oRm.class("thcLabel");
            if (bSortable) {
                oRm.class("thcSortable");
                oRm.attr("role", "button");
                oRm.attr("tabindex", "0");
                oRm.attr("aria-label", `Sort by ${oControl.getText()}`);
            }
            oRm.openEnd();
            oRm.text(oControl.getText());
            oRm.close("span");

            if (bSortable && sSortState !== "none") {
                oRm.openStart("span");
                oRm.class("thcSortArrow");
                oRm.attr("aria-hidden", "true");
                oRm.openEnd();
                oRm.icon(IconPool.getIconURI(sSortState === "asc" ? "sort-ascending" : "sort-descending"));
                oRm.close("span");
            }
            oRm.close("span");

            if (bCanFilter) {
                oRm.openStart("button");
                oRm.class("thcChevronSlot");
                oRm.attr("type", "button");
                oRm.attr("aria-label", `Filter ${oControl.getText()}`);
                oRm.attr("title", `Filter ${oControl.getText()}`);
                oRm.openEnd();
                oRm.icon(IconPool.getIconURI("slim-arrow-down"));
                oRm.close("button");
            }

            oRm.close("div");
        }
    };

    public init(): void {
        this.attachBrowserEvent("click", this._onBrowserClick as any, this);
        this.attachBrowserEvent("keydown", this._onBrowserKeyDown as any, this);
    }

    public exit(): void {
        this.detachBrowserEvent("click", this._onBrowserClick as any, this);
        this.detachBrowserEvent("keydown", this._onBrowserKeyDown as any, this);
        this._oPopover?.destroy();
        this._oPopover = null;
    }

    private _onBrowserClick(oEvent: any): void {
        const oTarget = oEvent.target as HTMLElement;
        if (oTarget.closest(".thcChevronSlot")) {
            oEvent.preventDefault();
            oEvent.stopPropagation();
            if (this._oPopover?.isOpen()) {
                this._oPopover.close();
            } else {
                this._openFilterPopover();
            }
            return;
        }

        // The entire header is a sort target, mirroring Windows File Explorer.
        // Close an open filter panel before changing the sort state.
        if (this.getSortable() && !oTarget.closest(".thcChevronSlot")) {
            oEvent.preventDefault();
            if (this._oPopover?.isOpen()) {
                this._oPopover.close();
            }
            this._cycleSort();
        }
    }

    private _onBrowserKeyDown(oEvent: any): void {
        const oTarget = oEvent.target as HTMLElement;
        if (this.getSortable() && oTarget.closest(".thcLabel") && (oEvent.key === "Enter" || oEvent.key === " ")) {
            oEvent.preventDefault();
            this._cycleSort();
        }
    }

    private _cycleSort(): void {
        const sCurrent = this.getSortState() as SortState;
        const sNext: SortState = sCurrent === "none" ? "asc" : sCurrent === "asc" ? "desc" : "none";
        this.fireSortChange({
            columnKey: this.getColumnKey(),
            sortField: this.getSortField(),
            sortState: sNext
        });
    }

    private _openFilterPopover(): void {
        const oPopover = this._getPopover();
        this._buildPopoverContent();
        oPopover.openBy(this);
    }

    private _getPopover(): ResponsivePopover {
        if (!this._oPopover) {
            this._oPopover = new ResponsivePopover({
                title: this.getText(),
                placement: "Bottom",
                contentWidth: "20rem",
                beginButton: new Button({
                    text: this._getText("filterClear", "Clear"),
                    press: () => {
                        this.fireFilterClear({ columnKey: this.getColumnKey() });
                        this._oPopover?.close();
                    }
                }),
                endButton: new Button({
                    text: this._getText("filterApply", "Apply"),
                    type: "Emphasized",
                    press: () => this._applyFilter()
                })
            });
            this.addDependent(this._oPopover);
        }
        return this._oPopover;
    }

    private _buildPopoverContent(): void {
        const oPopover = this._getPopover();
        oPopover.destroyContent();
        this._oTextInput = null;
        this._oCategoryList = null;
        this._oDateRange = null;
        this._oSlaSelect = null;

        const sFilterType = this.getFilterType() as FilterType;
        const oValue = this.getFilterValue() || {};

        if (sFilterType === "text") {
            this._oTextInput = new Input({
                width: "100%",
                placeholder: this._getText("filterSearchPlaceholder", "Search..."),
                value: (oValue as TextFilterValue).query || ""
            });
            const oBox = new VBox({ items: [this._oTextInput] });
            oBox.addStyleClass("sapUiSmallMargin");
            oPopover.addContent(oBox);
            return;
        }

        if (sFilterType === "category") {
            const aSelected = (oValue as CategoryFilterValue).selected || [];
            this._oCategoryList = new List({ mode: "MultiSelect", includeItemInSelection: true });
            this._parseCategoryOptions().forEach((sOption) => {
                const oItem = new StandardListItem({ title: sOption, selected: aSelected.includes(sOption) });
                oItem.data("filterValue", sOption);
                this._oCategoryList!.addItem(oItem);
            });
            const oBox = new VBox({ items: [this._oCategoryList] });
            oBox.addStyleClass("sapUiSmallMargin");
            oPopover.addContent(oBox);
            return;
        }

        if (sFilterType === "dateRange") {
            const oDateValue = oValue as DateFilterValue;
            this._oDateRange = new DateRangeSelection({
                width: "100%",
                displayFormat: "medium",
                dateValue: this._asDate(oDateValue.from),
                secondDateValue: this._asDate(oDateValue.to)
            });
            const oBox = new VBox({
                items: [new Label({ text: this._getText("filterDueDateRange", "Due date range") }), this._oDateRange]
            });
            oBox.addStyleClass("sapUiSmallMargin");
            oPopover.addContent(oBox);
            return;
        }

        if (sFilterType === "slaStatus") {
            this._oSlaSelect = new Select({
                width: "100%",
                selectedKey: (oValue as SlaFilterValue).selection || "all",
                items: [
                    new Item({ key: "all", text: this._getText("slaAll", "All") }),
                    new Item({ key: "overdue", text: this._getText("slaOverdue", "Overdue") }),
                    new Item({ key: "onTrack", text: this._getText("slaOnTrack", "On Track") })
                ]
            });
            const oBox = new VBox({ items: [this._oSlaSelect] });
            oBox.addStyleClass("sapUiSmallMargin");
            oPopover.addContent(oBox);
        }
    }

    private _applyFilter(): void {
        const sFilterType = this.getFilterType() as FilterType;
        let oValue: TextFilterValue | CategoryFilterValue | DateFilterValue | SlaFilterValue = {};

        if (sFilterType === "text") {
            oValue = { query: this._oTextInput?.getValue().trim() || "" };
        } else if (sFilterType === "category") {
            oValue = {
                selected: (this._oCategoryList?.getSelectedItems() || [])
                    .map((oItem) => oItem.data("filterValue") as string)
            };
        } else if (sFilterType === "dateRange") {
            oValue = {
                from: this._oDateRange?.getDateValue() || null,
                to: this._oDateRange?.getSecondDateValue() || null
            };
        } else if (sFilterType === "slaStatus") {
            oValue = { selection: (this._oSlaSelect?.getSelectedKey() || "all") as SlaFilterValue["selection"] };
        }

        this.fireFilterChange({
            columnKey: this.getColumnKey(),
            filterType: sFilterType,
            value: oValue
        });
        this._oPopover?.close();
    }

    private _getText(sKey: string, sFallback: string): string {
        const oBundle = (this.getModel("i18n") as any)?.getResourceBundle();
        return oBundle ? oBundle.getText(sKey) : sFallback;
    }

    private _parseCategoryOptions(): string[] {
        try {
            const aOptions = JSON.parse(this.getCategoryOptions());
            return Array.isArray(aOptions) ? aOptions.filter((sValue) => typeof sValue === "string") : [];
        } catch (_oError) {
            return [];
        }
    }

    private _asDate(vDate: Date | string | null | undefined): Date | undefined {
        if (!vDate) {
            return undefined;
        }
        const oDate = vDate instanceof Date ? vDate : new Date(vDate);
        return Number.isNaN(oDate.getTime()) ? undefined : oDate;
    }
}
